name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi9/ubi:latest
      options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Podman
      run: |
        dnf install -y podman

    - name: Login to gchr.io
      run: |
        podman login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

    - name: Build and Push Docker Image
      run: |
        podman build -f Containerfile -t gchr.io/${{ github.actor }}/my-image:latest .
        podman push gchr.io/${{ github.actor }}/my-image:latest
