name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: DeterminateSystems/nix-installer-action@main

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to gchr.io
      run: |
        nix run nixpkgs#buildah -- login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

    - name: Build and Push Docker Image
      run: |
        nix run nixpkgs#buildah -- buildah build -f Containerfile -t gchr.io/${{ github.actor }}/my-image:latest .
        nix run nixpkgs#buildah -- buildah push gchr.io/${{ github.actor }}/my-image:latest
