name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  TAG: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi9/ubi:latest
      options: --privileged
    permissions:
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Podman
      run: |
        dnf install -y podman

    - name: Login to GitHub Container Registry
      run: |
        podman login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

    - name: Build and Push Docker Image
      run: |
        podman build -f Containerfile -t ${{ env.TAG }} .
        podman push ${{ env.TAG }}
