name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: quay.io/buildah/stable

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to gchr.io
      run: |
        buildah login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

    - name: Build and Push Docker Image
      run: |
        buildah build -f Containerfile -t gchr.io/${{ github.actor }}/my-image:latest .
        buildah push gchr.io/${{ github.actor }}/my-image:latest
